name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: weishaodaren/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 6dbfcaeb6159ef2ca35208b6c1a66886
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
